name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  check:
    name: check ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
          - runner: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          persist-credentials: false
      - uses: jdx/mise-action@082e167e38ac2494dfb62e04240eac1f2a2d30dc
        with:
          install_args: rust
      - name: test
        run: cargo test --release --locked --target ${{ matrix.target }}
      - name: clippy
        run: cargo clippy --all-targets --release --locked --target ${{ matrix.target }} -- -D warnings
